# Generated by Django 5.1.7 on 2025-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminginfo', '0002_remove_admin_password_remove_admin_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=2025, max_length=10, unique=True, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
