# Generated by Django 5.1.7 on 2025-05-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminginfo', '0003_remove_admin_user_admin_password_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_superuser',
        ),
    ]
