# Generated by Django 5.1.7 on 2025-05-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminginfo', '0005_admin_is_active_admin_is_staff_admin_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
