# Generated by Django 5.1.7 on 2025-05-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminginfo', '0006_remove_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='password'),
            preserve_default=False,
        ),
    ]
