# Generated by Django 5.1.7 on 2025-05-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminginfo', '0009_admin_is_active_admin_is_staff_admin_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='titre')),
                ('corps', models.TextField(max_length=5000, verbose_name="Corps de l'annonce")),
                ('piece', models.CharField(max_length=200)),
                ('type_piece', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
