# Generated by Django 5.1.1 on 2025-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_teacher', models.CharField(max_length=30, verbose_name='nom Enseignant')),
                ('prenom_teacher', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=10)),
                ('discipline', models.CharField(max_length=15)),
            ],
        ),
    ]
