# Generated by Django 5.2.1 on 2025-06-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieressource',
            name='extensions_associees',
            field=models.CharField(blank=True, help_text='Extensions de fichiers associées (séparées par des virgules, ex: pdf,docx,odt)', max_length=200),
        ),
    ]
