# Generated by Django 5.1.7 on 2025-05-21 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15, unique=True, verbose_name='nom_forum')),
                ('description', models.TextField(max_length=200, verbose_name='description_forum')),
                ('profil', models.CharField(max_length=100, verbose_name='profil_forum')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums_crees', to=settings.AUTH_USER_MODEL, verbose_name='createur_forum')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'ordering': ['nom'],
            },
        ),
    ]
