# Generated by Django 5.1.7 on 2025-05-28 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='forums_rejoints', to=settings.AUTH_USER_MODEL),
        ),
    ]
