# Generated by Django 5.1.1 on 2025-02-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echange', '0001_initial'),
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageEnvoie',
        ),
        migrations.CreateModel(
            name='MessageRecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.TextField(max_length='300', verbose_name='message')),
                ('receiveEtudiantt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Etudiants.etudiant', verbose_name='reception Etudiant')),
            ],
        ),
    ]
