# Generated by Django 5.1.1 on 2025-02-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echange', '0002_rename_message_messageenvoie_messagerecu'),
        ('Etudiants', '0002_etudiant_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerecu',
            name='receiveEtudiantt',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.TextField(max_length='300', verbose_name='message')),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='Etudiants.etudiant')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='envoie', to='Etudiants.etudiant')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageEnvoie',
        ),
        migrations.DeleteModel(
            name='MessageRecu',
        ),
    ]
