# Generated by Django 5.1.7 on 2025-04-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Echange', '0005_alter_commentaire_auteur_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='group',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
