# Generated by Django 5.1.1 on 2025-02-10 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Etudiants', '0003_etudiant_avatar_etudiant_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='nom_group')),
                ('description', models.TextField(max_length=300, verbose_name='description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='creationGroup')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='createur', to='Etudiants.etudiant')),
                ('members', models.ManyToManyField(related_name='membres', to='Etudiants.etudiant')),
            ],
        ),
    ]
