# Generated by Django 5.1.1 on 2025-02-10 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0003_etudiant_avatar_etudiant_statut'),
        ('Groupe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createur', to='Etudiants.etudiant'),
        ),
    ]
