# Generated by Django 5.1.1 on 2025-02-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groupe', '0002_alter_group_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profil',
            field=models.CharField(default=0, max_length=255, verbose_name='profilGroup'),
            preserve_default=False,
        ),
    ]
