# Generated by Django 5.1.7 on 2025-04-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Echange', '0006_remove_message_receiver_remove_message_sender_and_more'),
        ('Groupe', '0003_group_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
