# Generated by Django 5.1.1 on 2025-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=8, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom Etudiant')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom Etudiant')),
                ('filiere', models.CharField(max_length=3, verbose_name='Filiere')),
                ('niveau', models.IntegerField(verbose_name='Niveau')),
                ('inscrit', models.IntegerField(verbose_name="Annee d'entree")),
            ],
        ),
    ]
