# Generated by Django 5.1.1 on 2025-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='password',
            field=models.CharField(default=0, max_length=20, verbose_name='mdp Etudiant'),
            preserve_default=False,
        ),
    ]
