# Generated by Django 5.1.1 on 2025-02-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0002_etudiant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='avatar',
            field=models.CharField(default=0, max_length=20, verbose_name='profil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(default=0, max_length=10, verbose_name='statut'),
            preserve_default=False,
        ),
    ]
