# Generated by Django 5.1.7 on 2025-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0003_etudiant_avatar_etudiant_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=9, unique=True, verbose_name='Matricule'),
        ),
    ]
