# Generated by Django 5.1.7 on 2025-04-23 06:34

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0004_alter_etudiant_matricule'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='etudiant',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='inscrit',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='statut',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='inscription',
            field=models.CharField(default=0, max_length=4, verbose_name="annee d'inscription"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mail',
            field=models.EmailField(default=0, max_length=50, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='profil',
            field=models.CharField(default=2025, max_length=255, verbose_name='profil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=10, unique=True, verbose_name='matricule'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(max_length=10, verbose_name='mot de passe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=255, verbose_name='prenom'),
        ),
    ]
