# Generated by Django 5.1.7 on 2025-04-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0005_alter_etudiant_managers_remove_etudiant_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
