# Generated by Django 5.1.7 on 2025-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0006_alter_etudiant_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=10, unique=True, verbose_name='identifiant'),
        ),
    ]
