# Generated by Django 5.1.7 on 2025-04-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0007_alter_etudiant_matricule'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='etudiant',
            managers=[
            ],
        ),
    ]
