# Generated by Django 5.1.7 on 2025-04-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0008_alter_etudiant_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
