# Generated by Django 5.1.7 on 2025-04-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0009_etudiant_is_admin_alter_etudiant_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='mail',
        ),
    ]
