# Generated by Django 5.1.7 on 2025-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0010_remove_etudiant_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
