# Generated by Django 5.1.7 on 2025-04-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0011_etudiant_is_staff_alter_etudiant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
