# Generated by Django 5.1.7 on 2025-04-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0012_alter_etudiant_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='inscription',
            new_name='annee',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(default=0, max_length=4, verbose_name='filiere'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(default=0, max_length=9, verbose_name='niveau'),
        ),
    ]
