# Generated by Django 5.1.7 on 2025-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0013_rename_inscription_etudiant_annee_etudiant_filiere_and_more'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.AddField(
            model_name='etudiant',
            name='forums',
            field=models.ManyToManyField(blank=True, related_name='membres', to='forum.forum', verbose_name="Forums d'appartenance"),
        ),
    ]
