# Generated by Django 5.1.7 on 2025-05-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0014_alter_etudiant_options_etudiant_forums'),
        ('forum', '0002_forum_membres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='forums',
            field=models.ManyToManyField(blank=True, related_name='inscrit', to='forum.forum', verbose_name="Forums d'appartenance"),
        ),
    ]
